config/routes.rb
Rails.application.routes.draw do
  root "pics#index"

  devise_for :users
  resources :pics do
    member do
      put "like", to: "pics#upvote"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
  belongs_to :user

  acts_as_votable

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pics = Pic.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: "Yesss! It was posted!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Congrats! Pic was updated!"
    else
      render :edit
    end
  end

  def destroy
    @pic.destroy
    redirect_to :index
  end

  def upvote
    @pic.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  private

    def pic_params
      params.require(:pic).permit(:title, :description, :image)
    end

    def find_pic
      @pic = Pic.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title InstaMK
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", "content" => "width=device-width, initial-scale=1, shrink-to-fit=no"}

    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
      .container
        = link_to "InstaMK", root_path, class: "navbar-brand"

        %button.navbar-toggler{:type => "button", "data-toggle" => "collapse", "data-target" => "#navbarNavAltMarkup", "aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
          %span.navbar-toggler-icon
        #navbarNavAltMarkup.collapse.navbar-collapse
          .navbar-nav.ml-auto
            - if user_signed_in?
              = link_to "Create Pic", new_pic_path, class: "nav-item nav-link"
              = link_to "Edit User", edit_user_registration_path, class: "nav-item nav-link"
              = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link"

            -else
              = link_to "Join", new_user_registration_path, class: "nav-item nav-link"
              = link_to "Log In", new_user_session_path, class: "nav-item nav-link"

    .container.my-4
      - unless flash.empty?
        - flash.each do |name, msg|
          = content_tag :div, msg, class: "alert alert-info"
        %hr.mb-4

      = yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
  - if @pic.errors.any?
    #errors
      %h2
        = pluralize(@pic.errors.count, "error")
        prevented this Pic from saving
      %ul
        - @pic.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :title, input_html: { class: "form-control" }
  .form-group
    = f.input :image, input_html: { class: "form-control" }
  .form-group
    = f.input :description, input_html: { class: "form-control" }

  = f.button :submit, class: "btn btn-primary"

app/views/pics/_pic.html.haml
.card
  - if pic.image?
    = link_to (image_tag pic.image.url(:medium), class: "card-img-top"), pic

  .card-body
    %h2.card-title= link_to pic.title, pic
    %p.card-text= truncate(pic.description, length: 50)

  .card-footer.text-muted
    %small
      Pic by
      = pic.user.email
    %br
    %small
      Posted
      = time_ago_in_words(pic.updated_at)
    - if user_signed_in?
      %br
      %small
        = link_to like_pic_path(pic), method: :put, class: "btn btn-default" do
          = fa_icon "thumbs-o-up"
          = pic.get_upvotes.size
    - else
      %br
      %small
        = fa_icon "thumbs-o-up"
        = pic.get_upvotes.size

app/views/pics/edit.html.haml
.row
  .col-md-8.mx-auto
    %h1 Fix Pic!

    - if @pic.image?
      .row
        = image_tag @pic.image.url(:medium), class: "mx-auto"

    = render "form"

app/views/pics/index.html.haml
.card-columns
  - @pics.each do |pic|
    = render "pic", :pic => pic

app/views/pics/new.html.haml
.row
  .col-md-8.mx-auto
    %h1 Post Pic!

    = render "form"

app/views/pics/show.html.haml
.card
  - if @pic.image?
    = image_tag @pic.image.url, class: "card-img-top"

  .card-body
    %h1.card-title= @pic.title

    %p.card-text= @pic.description

    -if user_signed_in?
      = link_to "Edit", edit_pic_path(@pic)
      = link_to "Delete", pic_path(@pic), method: :delete, data: { confirm: "Are you sure?" }

  .card-footer.text-muted
    %small
      Pic by
      = @pic.user.email
    %br
    %small
      Posted
      = time_ago_in_words(@pic.updated_at)
    -if user_signed_in?
      %br
      %small
        = link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do
          = fa_icon "thumbs-o-up"
          = @pic.get_upvotes.size